src/components/users/UserProfile.tsx
=> Add user data

src/components/users/UserProfile.tsx, src/utils/path.ts
=> Link to the manager's page

package-lock.json, package.json, src/pages/_app.tsx, src/pages/api/trpc/[trpc].ts, src/trpc/context.ts, src/trpc/router/index.ts, src/trpc/trpcBackend.ts, src/trpc/trpcClient.ts
=> Initialize TRPC

src/components/users/UserProfile.tsx
=> Layout needs some space under header

src/components/users/UserProfile.tsx
=> Text offsets are wrong

Dockerfile
=> ci(docker): copy prisma files

src/components/users/UserProfile.tsx
=> Group links

prisma/migrations/20230808154311_utc_timestamps/migration.sql, prisma/schema.prisma
=> Use utc-based timestamp by default

src/api-client/groups/group-api-hook.ts, src/api-client/groups/group-types.ts, src/api-client/users/user-api-hook.ts, src/components/CommonHeader.tsx, src/components/CommonHeaderPreview.tsx, src/components/InlineTrigger.tsx, src/components/groups/TeamChildren.tsx, src/components/groups/TeamPeople.tsx, src/components/groups/TeamProfile.tsx, src/components/groups/TeamProfilePreview.tsx, src/components/users/QuickSummary.tsx, src/components/users/UserContacts.tsx, src/components/users/UserProfile.tsx, src/components/users/UserProfilePreview.tsx, src/components/users/UserTeams.tsx, src/hooks/children-hooks.ts, src/schema/children-types.ts, src/trpc/router/children-router.ts, src/trpc/router/index.ts
=> Group preview popup

src/components/CommonHeader.tsx, src/components/CommonHeaderPreview.tsx, src/components/groups/TeamProfilePreview.tsx
=> Group preview in popup

package-lock.json, package.json, src/components/header/PageHeader.tsx, src/pages/_app.tsx, src/pages/groups/[groupId]/index.tsx, src/pages/groups/index.tsx, src/pages/services/index.tsx, src/pages/users/[userId]/index.tsx, src/pages/users/index.tsx, src/trpc/trpcClient.ts, src/utils/auth.ts, src/utils/createGetSSRProps.ts, src/utils/objKeys.ts, src/utils/path.ts, src/utils/utils.i18n/en.json, src/utils/utils.i18n/index.ts, src/utils/utils.i18n/ru.json
=> Api auth and error handler

package-lock.json, package.json, src/api-client/feedback/feedback-schemas.ts, src/api-client/feedback/feedback.i18n/en.json, src/api-client/feedback/feedback.i18n/index.ts, src/api-client/feedback/feedback.i18n/ru.json, src/components/feedback/FeedbackCreateForm.tsx, src/components/feedback/feedback.i18n/en.json, src/components/feedback/feedback.i18n/index.ts, src/components/feedback/feedback.i18n/ru.json, src/components/footer/PageFooter.tsx, src/components/footer/footer.i18n/en.json, src/components/footer/footer.i18n/ru.json, src/trpc/router/feedback-router.ts, src/trpc/router/index.ts, src/utils/forms.ts
=> Feedback button as in issues

CODEOWNERS
=> No codeowners

prisma/migrations/20230906080926_group_membership_role/migration.sql, prisma/schema.prisma
=> Group DB model

src/components/groups/TeamProfile.tsx, src/components/users/UserContacts.tsx, src/components/users/UserProfile.tsx, src/components/users/UserProfilePreview.tsx
=> Corporate devices in the user profile

.github/workflows/pr.yml, src/modules/group.test.ts
=> Test DB infrastructure

src/modules/search.methods.ts, src/trpc/router/index.ts, src/trpc/router/search-router.ts
=> Global search handler

prisma/seed.ts, src/components/services/AddServiceToUserForm.tsx, src/components/services/services.i18n/en.json, src/components/services/services.i18n/ru.json, src/components/users/UserContacts.tsx, src/components/users/UserPage.tsx, src/components/users/users.i18n/en.json, src/components/users/users.i18n/ru.json, src/modules/modules.i18n/en.json, src/modules/modules.i18n/ru.json, src/modules/service.method.ts, src/modules/service.schemas.ts, src/trpc/router/index.ts, src/trpc/router/service-router.ts
=> Inline form in contacts

src/components/users/UserContacts.tsx, src/components/users/UserPage.tsx
=> Remove timeline divider from profile

.husky/pre-push, src/components/groups/EditRolesModal.tsx, src/components/groups/TeamProfilePreview.tsx, src/components/groups/TransferGroupForm.tsx, src/components/groups/groups.i18n/en.json, src/components/groups/groups.i18n/ru.json, src/components/services/AddServiceToUserForm.tsx, src/components/services/services.i18n/en.json, src/components/services/services.i18n/ru.json, src/modules/group.hooks.ts, src/modules/group.methods.ts, src/modules/group.schemas.ts, src/modules/group.test.ts, src/modules/modules.i18n/en.json, src/modules/modules.i18n/ru.json, src/modules/service.hooks.ts, src/trpc/router/group-router.ts
=> Group transfer popup

src/components/groups/AddUserToTeamForm.tsx, src/components/groups/EditRolesModal.tsx, src/components/groups/GroupListItem.tsx, src/components/groups/GroupListItemEditable.tsx, src/components/groups/MembershipListItem.tsx, src/components/groups/RemoveUserFromGroupModal.tsx, src/components/groups/TeamChildren.tsx, src/components/groups/TeamPeople.tsx, src/components/groups/TransferGroupForm.tsx, src/components/groups/groups.i18n/en.json, src/components/groups/groups.i18n/ru.json, src/components/services/AddServiceToUserForm.tsx, src/components/users/AddTeamToUserForm.tsx, src/components/users/UserDevices.tsx, src/components/users/UserProfilePreview.tsx, src/components/users/UsersPage.tsx, src/modules/user.hooks.ts, src/modules/user.methods.ts, src/modules/user.schemas.ts, src/trpc/router/user-router.ts
=> Group preview

src/pages/index.tsx
=> Redirect to my profile from root

prisma/migrations/20230928100350_user_bonus_points/migration.sql, prisma/schema.prisma, src/components/NarrowSection.tsx, src/components/PageSep.tsx, src/components/services/AddServiceToUserForm.tsx, src/components/services/services.i18n/en.json, src/components/services/services.i18n/ru.json, src/components/users/UserBonusPoints.tsx, src/components/users/UserPage.tsx, src/components/users/users.i18n/en.json, src/components/users/users.i18n/ru.json
Resolve #192
- migration
- balance visualization
- stub balance change form
- user page layout refactoring
=> Bonus points in profile

src/components/Previews.tsx, src/components/UserGroupListItem.tsx, src/components/groups/EditRolesModal.tsx, src/components/groups/MembershipListItem.tsx, src/components/groups/RemoveUserFromGroupModal.tsx, src/components/groups/TeamPage.tsx, src/components/users/UserProfilePreview.tsx, src/components/users/UsersPage.tsx, src/context/preview-context.tsx, src/modules/group.methods.ts, src/modules/user.methods.ts, src/modules/user.types.ts
Related issues: in preparation for #191
=> Fetch data inside user preview

prisma/migrations/20231003150435_global_admins/migration.sql, prisma/schema.prisma, prisma/seed.ts, src/components/users/UserBonusPoints.tsx, src/components/users/UserContacts.tsx, src/components/users/UserPage.tsx, src/modules/modules.i18n/en.json, src/modules/modules.i18n/ru.json, src/modules/user.access.ts, src/modules/user.methods.ts, src/modules/user.types.ts, src/trpc/router/service-router.ts, src/trpc/router/user-router.ts, src/utils/access.ts, src/utils/auth.ts
=> Global admins

src/utils/auth.ts
=> Allow email account linking in oauth provider

package-lock.json, package.json, src/components/InlineGroupSelectForm.tsx, src/components/Link.tsx, src/components/groups/TeamChildren.tsx, src/components/groups/TeamProfilePreview.tsx, src/components/groups/groups.i18n/en.json, src/components/groups/groups.i18n/ru.json, src/components/users/UserProfilePreview.tsx
=> Inline forms in previews

src/components/groups/TeamsPage.tsx
=> Slightly better temporary team list layout

src/components/UserServiceListItem.tsx, src/components/services/AddServiceToUserForm.tsx, src/components/users/UserContacts.tsx, src/components/users/UserPage.tsx, src/components/users/UserProfilePreview.tsx, src/modules/service.hooks.ts, src/modules/service.method.ts, src/trpc/router/service-router.ts
=> Add and display user services

src/components/Previews.tsx
=> Preview headers are inconsistent

prisma/migrations/20231012151146_supervisors/migration.sql, prisma/schema.prisma, src/components/Previews.tsx, src/components/UserGroupListItem.tsx, src/components/groups/GroupListItem.tsx, src/components/groups/TeamPage.tsx, src/components/groups/TeamProfilePreview.tsx, src/components/users/UserPage.tsx, src/components/users/UserProfilePreview.tsx, src/context/preview-context.tsx, src/modules/group.methods.ts, src/modules/group.types.ts, src/modules/user.methods.ts, src/modules/user.types.ts, src/utils/types.ts
=> Supervisors for groups and users

src/components/users/UserPage.tsx
=> User profile paddings

src/modules/user.methods.ts
=> Order groups in membership query

src/components/Link.tsx, src/components/groups/TeamPage.tsx
=> Remove Link props from DOM

src/components/UserServiceListItem.tsx, src/components/users/UserContacts.tsx
=> Null in crew contact link

src/pages/users/email/[userEmail]/index.tsx
=>  Get profile via email route

package-lock.json, package.json, prisma/migrations/20231101094038_api_tokens/migration.sql, prisma/schema.prisma, src/modules/userMethods.ts, src/pages/api/rest/[trpc].ts, src/trpc/router/restRouter.ts, src/trpc/trpcBackend.ts
Resolve #269 
```
$ curl -v -H "X-Api-Key: cba9f9a0-06db-450c-840c-6e83ef9bb4f6" -X GET "http://localhost:3000/api/rest/users?email=user@example.com" 
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 127.0.0.1:3000...
* Connected to localhost (127.0.0.1) port 3000 (#0)
> GET /api/rest/users?email=user@example.com HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/8.1.2
> Accept: */*
> X-Api-Key: cba9f9a0-06db-450c-840c-6e83ef9bb4f6
> 
< HTTP/1.1 200 OK
< set-cookie: next-auth.csrf-token=b43a73268d567ad62904a78f1a721b582a1c7c29897f4f2ba9419e1789158461%7Cd3f66247118d7572d3e631d171d482cf959102c838b7910f07b139318ea0bc76; Path=/; HttpOnly; SameSite=Lax
< set-cookie: next-auth.callback-url=http%3A%2F%2Flocalhost%3A3000; Path=/; HttpOnly; SameSite=Lax …
```
=> Webhook API

prisma/migrations/20231102113835_bonus_points_constraint/migration.sql, src/trpc/router/restRouter.ts, src/utils/auth.ts
=> Bonus points REST API

.github/workflows/manual_release.yml, .github/workflows/publish.yml, .github/workflows/release.yml, .github/workflows/release_notify.yml
=> Workflows: fix secrets, add release_notify

src/modules/group.test.ts, src/modules/groupMethods.ts, src/modules/modules.i18n/en.json, src/modules/modules.i18n/ru.json, src/modules/userMethods.ts
=> Disallow unarchiving group when parent is archived

src/components/UserBonusPoints/UserBonusPoints.tsx, src/components/UserPage/UserPage.tsx, src/modules/modules.i18n/en.json, src/modules/modules.i18n/ru.json, src/modules/userAccess.ts, src/modules/userMethods.ts, src/trpc/router/userRouter.ts
=> Hide bonus points from user page

src/modules/userMethods.ts
=> Bonus history reverse order

src/components/UserServiceListItem.tsx
=> Service links don't work

src/components/InlineGroupSelectForm.tsx, src/components/UserMembershipsList/UserMembershipsList.tsx, src/modules/groupMethods.ts, src/modules/groupSchemas.ts
=> Teams in add team Popup are not filtered by teams with participation

src/components/BonusPointsBalanceModal/BonusPointsBalanceModal.tsx, src/components/BonusPointsHistory/BonusPointsHistory.tsx
=> Show bonus points value in history

src/components/BonusAchievementComboBox/BonusAchievementComboBox.tsx, src/components/GroupComboBox/GroupComboBox.tsx, src/components/OrganizationUnitComboBox/OrganizationUnitComboBox.tsx, src/components/UserComboBox/UserComboBox.tsx
=> Remove onBlur handlers from comboboxes

src/components/UserPage/UserPage.tsx, src/modules/modules.i18n/en.json, src/modules/modules.i18n/ru.json, src/modules/userAccess.ts, src/modules/userMethods.ts, src/trpc/router/userRouter.ts
=> User can deactivate his profile

src/components/BonusAchievementComboBox/BonusAchievementComboBox.tsx, src/components/GroupComboBox/GroupComboBox.tsx, src/components/OrganizationUnitComboBox/OrganizationUnitComboBox.tsx, src/components/UserComboBox/UserComboBox.tsx
=> Hide combobox dropdowns on click outside

src/components/UserBonusPoints/UserBonusPoints.i18n/en.json, src/components/UserBonusPoints/UserBonusPoints.i18n/ru.json, src/components/UserBonusPoints/UserBonusPoints.tsx
=> Change texts of the bonus program

src/components/GroupTreeViewNode.tsx
=> Tree view node should be fully clickable

src/utils/auth.ts
=> Check additional emails during user auth

src/components/DeactivateProfileForm/DeactivateProvileForm.tsx, src/components/UserPage/UserPage.tsx, src/modules/group.test.ts, src/modules/modules.i18n/en.json, src/modules/modules.i18n/ru.json, src/modules/userAccess.ts, src/modules/userHooks.ts, src/modules/userMethods.ts, src/modules/userSchemas.ts, src/modules/userTypes.ts, src/trpc/router/userRouter.ts
=> Rethrow external user operation error

src/trpc/router/restRouter.ts
=> User update REST endpoint

package-lock.json, package.json, src/components/LayoutMain.tsx, src/components/OfflineBanner/OfflineBanner.i18n/en.json, src/components/OfflineBanner/OfflineBanner.i18n/index.ts, src/components/OfflineBanner/OfflineBanner.i18n/ru.json, src/components/OfflineBanner/OfflineBanner.tsx, src/pages/api/health.tsx
=> Offline detector

src/trpc/router/restRouter.ts
=> Rest api should expect emails, not ids

prisma/migrations/20240212104145_membership_percentage/migration.sql, prisma/schema.prisma, src/components/AddUserToTeamForm/AddUserToTeamForm.i18n/en.json, src/components/AddUserToTeamForm/AddUserToTeamForm.i18n/ru.json, src/components/AddUserToTeamForm/AddUserToTeamForm.tsx, src/components/InlineTrigger.tsx, src/components/MembershipGroupListItemEditable.tsx, src/components/MembershipUserListItemEditable.tsx, src/components/PopupTrigger.tsx, src/modules/modules.i18n/en.json, src/modules/modules.i18n/ru.json, src/modules/userMethods.ts, src/modules/userSchemas.ts, src/trpc/router/userRouter.ts
=> Team partial membership

prisma/migrations/20240212130156_hirestreamid_instead_of_heirestream_in_vacancy/migration.sql, prisma/schema.prisma, src/components/CreateVacancyModal/CreateVacancyModal.tsx, src/modules/vacancyMethods.ts, src/modules/vacancySchemas.ts, src/trpc/router/restRouter.ts, src/trpc/router/router.i18n/en.json, src/trpc/router/router.i18n/index.ts, src/trpc/router/router.i18n/ru.json, src/utils/hireIntegration.ts
=> Rest api for vacancies

package.json
=> Fix prisma seed script

src/components/AddUserToTeamForm/AddUserToTeamForm.tsx, src/components/PopupTrigger.tsx, src/hooks/useBoolean.ts
=> Member form should be cleared after submit

src/components/AddUserToTeamForm/AddUserToTeamForm.tsx
=> Some of participants can't be added to project

src/trpc/router/restRouter.ts
=> Add percentage to crew team API

src/modules/modules.i18n/en.json, src/modules/modules.i18n/ru.json, src/modules/vacancyMethods.ts, src/modules/vacancySchemas.ts, src/modules/vacancyTypes.ts, src/trpc/router/restRouter.ts
=> Update vacancy API to allow listing without hire stream filter

src/trpc/router/restRouter.ts
=> Rest api: image for groups users

src/components/ExportTeamMembers/ExportTeamMembers.i18n/en.json, src/components/ExportTeamMembers/ExportTeamMembers.i18n/index.ts, src/components/ExportTeamMembers/ExportTeamMembers.i18n/ru.json, src/components/ExportTeamMembers/ExportTeamMembers.tsx, src/components/TeamProfilePreview/TeamProfilePreview.tsx, src/utils/csv.test.ts, src/utils/csv.ts, src/utils/downloadAsFile.ts
Resolve #492 
```
Full name,Email,Roles,Membership percentage
Admin,admin@taskany.org,"Designer, Programmer",50
```
=> Team CSV Export

src/modules/groupMethods.ts, src/trpc/router/restRouter.ts
=> Rest api: group request for multiple ids

prisma/seed.ts, src/components/TeamVacancies/TeamVacancies.tsx, src/modules/vacancyMethods.ts, src/trpc/router/restRouter.ts
=> Send total count in vacancy list response

src/components/OfflineBanner/OfflineBanner.tsx
=> Offline bar from bricks

.eslintrc.js
=> ESLint: enable jsx-curly-brace-presence 

src/modules/vacancyMethods.ts, src/modules/vacancySchemas.ts, src/trpc/router/restRouter.ts
=> Filter vacancies by multiple statuses

src/components/AddRoleToMembershipForm/AddRoleToMembershipForm.tsx
=> [crash] TypeError: Cannot read properties from undefined

src/components/VacancyListItem.tsx, src/config.ts, src/modules/hireIntegrationMethods.ts
=> Vacancy should have a link to hire candidates page

src/components/ExportTeamMembers/ExportTeamMembers.i18n/en.json, src/components/ExportTeamMembers/ExportTeamMembers.i18n/ru.json, src/components/ExportTeamMembers/ExportTeamMembers.tsx, src/modules/groupMethods.ts, src/modules/modules.i18n/en.json, src/modules/modules.i18n/ru.json, src/trpc/router/groupRouter.ts, src/utils/objByKey.ts
=> CSV: Export subgroups

prisma/migrations/20240227155704_app_config/migration.sql, prisma/schema.prisma, prisma/seed.ts, src/components/LayoutMain.tsx, src/modules/appConfigMethods.ts, src/modules/appConfigTypes.ts, src/pages/_app.tsx, src/trpc/router/appConfigRouter.ts, src/trpc/router/index.ts, src/utils/createGetSSRProps.ts
Resolve #548 
https://github.com/taskany-inc/crew/assets/9020793/fb12f73c-98cc-4272-8713-e6a7b42dc393
=> Custom logo via plugins (Crew)

prisma/seed.ts
=> Fix app config seed

src/modules/userMethods.ts
=> Do not send user title to external service

src/components/ArchiveGroup/ArchiveGroup.i18n/en.json, src/components/ArchiveGroup/ArchiveGroup.i18n/index.ts, src/components/ArchiveGroup/ArchiveGroup.i18n/ru.json, src/components/ArchiveGroup/ArchiveGroup.tsx, src/components/EditRolesModal/EditRolesModal.tsx, src/components/GroupListItem.tsx, src/components/GroupListItemEditable.tsx, src/components/MembershipGroupListItem/MembershipGroupListItem.tsx, src/components/TeamChildren/TeamChildren.tsx, src/components/TeamProfilePreview/TeamProfilePreview.tsx, src/components/TeamSettingsPage/TeamSettingsPage.tsx, src/components/TransferGroupForm/TransferGroupForm.tsx, src/modules/groupAccess.ts, src/modules/groupMethods.ts, src/modules/modules.i18n/en.json, src/modules/modules.i18n/ru.json, src/trpc/router/groupRouter.ts
=> Archive group access limited

src/modules/deviceMethods.ts
=> Device suggestions should be case insensitive

src/components/TeamVacancies/TeamVacancies.tsx, src/modules/vacancyMethods.ts, src/modules/vacancySchemas.ts, src/trpc/router/restRouter.ts
=> Add vacancy filter by hiring manager, hr, closedAt, team

src/components/VacancyListItem.tsx, src/modules/groupMethods.ts, src/modules/groupSchemas.ts, src/trpc/router/restRouter.ts
=> Filter for having vacancies in groups

src/modules/vacancyMethods.ts, src/modules/vacancySchemas.ts, src/trpc/router/restRouter.ts
=> Instead hrs vacancies filter by hiring managers

src/components/CreateUserModal/CreateUserModal.i18n/en.json, src/components/CreateUserModal/CreateUserModal.i18n/ru.json, src/components/CreateUserModal/CreateUserModal.tsx, src/modules/userMethods.ts, src/modules/userSchemas.ts
=> Checkbox to user create dialog - create account

.github/workflows/codeql-analysis.yml, .github/workflows/pr.yml, .github/workflows/publish.yml, next.config.js, package-lock.json, package.json
=> Ignore sentry warnings during build

src/components/TeamProfilePreview/TeamProfilePreview.tsx, src/components/TeamVacancies/TeamVacancies.tsx, src/components/UpdateVacancyModal/UpdateVacancyModal.tsx, src/components/VacancyListItemEditable/VacancyListItemEditable.tsx, src/modules/groupMethods.ts, src/modules/groupTypes.ts, src/modules/modules.i18n/en.json, src/modules/modules.i18n/ru.json, src/modules/modules.test.ts, src/modules/vacancyHooks.ts, src/modules/vacancyTypes.ts, src/utils/testDbData.ts
=> Command archive doesn't affect vacancies

src/components/CreateGroupModal/CreateGroupModal.tsx, src/components/CreateUserModal/CreateUserModal.tsx, src/components/PageHeaderActionButton/PageHeaderActionButton.tsx, src/modules/globalAccess.ts, src/trpc/router/groupRouter.ts
=> Allow vTeam creation to everyone

package-lock.json, package.json, tsconfig.json
=> Install typescript plugin for css modules

src/modules/userMethods.ts
=> Hide user bonus points in responses

prisma/migrations/20240328100736_service_display_name/migration.sql, prisma/schema.prisma, prisma/seed.ts, src/components/AddAchievementModal/AddAchievementModal.i18n/en.json, src/components/AddAchievementModal/AddAchievementModal.i18n/ru.json, src/components/AddServiceToUserForm/AddServiceToUserForm.tsx, src/components/CreateUserModal/CreateUserModal.i18n/en.json, src/components/CreateUserModal/CreateUserModal.i18n/ru.json, src/components/CreateUserModal/CreateUserModal.tsx, src/components/UserContacts/UserContacts.tsx, src/components/UserServiceListItem.tsx, src/modules/modules.i18n/en.json, src/modules/modules.i18n/ru.json, src/modules/serviceMethods.ts, src/modules/userMethods.ts, src/modules/userSchemas.ts, src/trpc/router/restRouter.ts
=> Create user API

src/modules/achievementMethods.ts, src/modules/achievementSchemas.ts, src/trpc/router/restRouter.ts, src/utils/index.ts
=> API to add achievements

src/trpc/router/groupRouter.ts
=> Fix prisma is not defind in group edit

.eslintrc.js, src/modules/organizationUnitMethods.ts, src/modules/organizationUnitSchemas.ts, src/modules/serviceMethods.ts, src/modules/serviceSchemas.ts, src/modules/userMethods.ts, src/modules/userSchemas.ts, src/trpc/router/restRouter.ts, src/utils/assertNever.ts
=> Update user API

src/components/UserPage/UserPage.i18n/en.json, src/components/UserPage/UserPage.i18n/ru.json, src/components/UserPage/UserPage.tsx, src/modules/userMethods.ts, src/modules/userTypes.ts
=> Show supervised people and groups in user profile page

src/components/UserContacts/UserContacts.tsx
=> User contacts bug

prisma/migrations/20240412135039_locale_in_user_settings/migration.sql, prisma/schema.prisma, src/components/LayoutMain.tsx, src/components/PageFooter/PageFooter.i18n/en.json, src/components/PageFooter/PageFooter.i18n/ru.json, src/components/PageFooter/PageFooter.tsx, src/components/PageHeader/PageHeader.tsx, src/components/PageHeaderActionButton/PageHeaderActionButton.tsx, src/components/UserSettingsPage/UserSettingsPage.i18n/en.json, src/components/UserSettingsPage/UserSettingsPage.i18n/ru.json, src/components/UserSettingsPage/UserSettingsPage.tsx, src/modules/userHooks.ts, src/modules/userSchemas.ts, src/modules/userTypes.ts, src/utils/getLang.ts
=> Locale in user settings

src/modules/userMethods.ts
=> Get user by service id throws error

prisma/migrations/20240422130120_ahcievement_info_in_bonus_history/migration.sql, prisma/schema.prisma, src/components/BonusPointsBalanceModal/BonusPointsBalanceModal.tsx, src/modules/bonusPointsMethods.ts, src/modules/bonusPointsSchemas.ts, src/modules/bonusPointsTypes.ts
=> Add category information to an achievement

src/components/DeleteUserDeviceModal/DeleteUserDeviceModal.tsx, src/components/UserDeviceListItem.tsx, src/components/UserDevices/UserDevices.tsx
Resolve #708 
https://github.com/taskany-inc/crew/assets/95316053/d07991e5-df41-41c7-97b4-7af5fbdba018
=> Return deviceId to users devices list

src/components/UserDevices/UserDevices.tsx, src/modules/modules.i18n/en.json, src/modules/modules.i18n/ru.json, src/modules/userAccess.ts, src/modules/userMethods.ts, src/modules/userTypes.ts, src/trpc/router/deviceRouter.ts
Resolve #705 
https://github.com/taskany-inc/crew/assets/95316053/bd666ba5-1499-470c-a8bc-e59ee0f9b083
=> Allow user to add a device

src/components/AddAchievementModal/AddAchievementModal.tsx
Resolve #643 
https://github.com/taskany-inc/crew/assets/95316053/abb49fbc-d320-4b81-acb7-79f8bc30dabd
=> There is no error message when focusing in the field

prisma/migrations/20240426163136_bonus_rule_for_crew_achievement/migration.sql, prisma/schema.prisma, src/config.ts, src/modules/bonusPointsMethods.ts
=> Rules to add achievements for bonus categories

prisma/migrations/20240425101337_add_login_to_user/migration.sql, prisma/schema.prisma, prisma/seed.ts, src/components/UserContacts/UserContacts.tsx, src/components/UserPage/UserPage.tsx, src/modules/userMethods.ts, src/pages/[userLogin]/index.tsx, src/trpc/router/userRouter.ts
=> Unique logins for users

src/modules/achievementMethods.ts
=> Bonuses add only for first achievement bug

src/modules/bonusPointsMethods.ts
=> Bonuses amount sums by all users

src/modules/bonusPointsMethods.ts
=> Achievement given even if bonuses amount not enough

package-lock.json, package.json, prisma/migrations/20240427123920_history_events/migration.sql, prisma/schema.prisma, src/components/AddAchievementModal/AddAchievementModal.tsx, src/modules/achievementMethods.ts, src/modules/achievementSchemas.ts, src/modules/bonusPointsMethods.ts, src/modules/groupMethods.ts, src/modules/historyEventMethods.ts, src/modules/historyEventTypes.ts, src/modules/roleMethods.ts, src/modules/userMethods.ts, src/modules/vacancyMethods.ts, src/trpc/router/achievementRouter.ts, src/trpc/router/bonusPointsRouter.ts, src/trpc/router/deviceRouter.ts, src/trpc/router/groupRouter.ts, src/trpc/router/restRouter.ts, src/trpc/router/roleRouter.ts, src/trpc/router/serviceRouter.ts, src/trpc/router/userRouter.ts, src/trpc/router/vacancyRouter.ts, src/trpc/trpcBackend.ts, src/trpc/trpcContext.ts, src/utils/createGetSSRProps.ts, src/utils/dropUnchangedValuesFromEvents.test.ts, src/utils/dropUnchangedValuesFromEvents.tsx
=> History items

prisma/migrations/20240508102304_view_history_role/migration.sql, prisma/schema.prisma, prisma/seed.ts, src/components/PageHeader/PageHeader.i18n/en.json, src/components/PageHeader/PageHeader.i18n/ru.json, src/components/PageHeader/PageHeader.tsx, src/components/UserPage/UserPage.i18n/en.json, src/components/UserPage/UserPage.i18n/ru.json, src/components/UserPage/UserPage.tsx, src/hooks/useRouter.ts, src/modules/historyEventMethods.ts, src/modules/modules.i18n/en.json, src/modules/modules.i18n/ru.json, src/modules/userAccess.ts, src/modules/userMethods.ts, src/trpc/router/historyEventsRouter.ts
=> Access scope for reading history events

prisma/migrations/20240513121415_add_service_number/migration.sql, prisma/schema.prisma, prisma/seed.ts, src/components/UserContacts/UserContacts.tsx, src/trpc/router/restRouter.ts
Resolve #737 
1) Need to use script
```sql
INSERT INTO "ExternalService" (name, icon)
VALUES ('ServiceNumber', 'IconReceiptOutline');
```
2) Set the `organizationUnitId` for API Tokens
=> Add serviceNumber to external routes

prisma/migrations/20240515104321_rule_in_bonus_history/migration.sql, prisma/schema.prisma, src/modules/achievementMethods.ts
=> Link bonus rule to bonusHistory

prisma/migrations/20240515110307_ext_achievement_id_in_bonus_rule/migration.sql, prisma/schema.prisma, src/modules/bonusPointsMethods.ts
=> Create a rule for some bonus activities, not only category

src/trpc/router/restRouter.ts
=> Return membership roles in GET /users/{login}

package-lock.json, package.json, prisma/schema.prisma, src/modules/searchMethods.ts, src/trpc/router/restRouter.ts
=> User lookup API

src/modules/userMethods.ts, src/modules/userSchemas.ts, src/trpc/router/restRouter.ts
=> Create a new method for updating users

src/modules/achievementMethods.ts
=> fix: wrong model id in bonus history record

src/trpc/router/restRouter.ts
=> Fix path to users bonus route

src/components/TeamPeople/TeamPeople.tsx, src/modules/groupMethods.ts, src/modules/modules.test.ts, src/trpc/router/groupRouter.ts
Resolve #770 
https://github.com/taskany-inc/crew/assets/95316053/31c2e670-e4b9-4bdd-81d7-602972323597
https://github.com/taskany-inc/crew/assets/95316053/c1334559-5c25-43c3-8158-512b7a27263d
=> Add people counter for teams

src/hooks/useRouter.ts
=> Page for scheduled deactivations on wrong address

src/components/PageHeader/PageHeader.tsx
=>  Visibility of scheduled deactivations link on header bug

src/components/NewScheduleDeactivationForm/NewScheduleDeactivationForm.tsx, src/trpc/router/scheduledDeactivationRouter.ts
=> Schedule deactivation bugs

src/modules/userMethods.ts, src/modules/userSchemas.ts, src/trpc/router/restRouter.ts, src/utils/getCorporateEmail.ts
=> Sync output schemas of user in rest api

package-lock.json, package.json
https://github.com/getsentry/sentry-javascript/pull/12131
Resolve #808
=> Fix @sentry/nextjs version

prisma/migrations/20240524152422_subsystem_events/migration.sql, prisma/schema.prisma, src/components/HistoryRecord/HistoryRecord.i18n/en.json, src/components/HistoryRecord/HistoryRecord.i18n/ru.json, src/components/HistoryRecord/HistoryRecord.tsx, src/components/UserActivityPage/UserActivityPage.tsx, src/modules/historyEventMethods.ts, src/modules/historyEventTypes.ts, src/modules/userSchemas.ts, src/utils/auth.ts
=> Create new accounts based on login, not on email

src/modules/userMethods.ts
=>  Edit user bug

src/components/UserPage/UserPage.tsx, src/modules/userMethods.ts, src/modules/userTypes.ts
=> Show RoleComboBox icon in both mode

src/components/UserMembershipsList/UserMembershipsList.tsx, src/modules/groupAccess.ts, src/trpc/router/groupRouter.ts, src/trpc/router/roleRouter.ts, src/trpc/router/userRouter.ts, src/trpc/router/vacancyRouter.ts
Resolve #833
https://github.com/taskany-inc/crew/assets/9020793/af49815a-93e4-422b-a691-698975ee7d00
=> Group administrator can't edit group

src/components/TeamSettingsPage/TeamSettingsPage.tsx
=> Group settings page visible by direct link

src/modules/bonusPointsMethods.ts
=> Wrong achievements amount

src/modules/userMethods.ts
=> Throw original error on accepting account request

src/modules/groupAccess.ts
=> Add current user to admin at creation Team

src/components/AdminPanel/AdminPanel.module.css, src/components/AdminPanel/AdminPanel.tsx
-   [ ] Refactor
Resolve #830 
https://github.com/taskany-inc/crew/assets/95316053/49b470ca-868e-4173-a15a-9aeafb4e6432
=> Beautify Admin Panel markup

src/utils/notifications/notifyPromise.ts
=> Humanize error messages on adding user to group

src/components/CreateGroupModal/CreateGroupModal.tsx, src/components/GroupComboBox/GroupComboBox.tsx, src/components/InlineGroupSelectForm.tsx, src/components/TeamChildren/TeamChildren.tsx, src/components/TeamProfilePreview/TeamProfilePreview.tsx, src/components/TeamSettingsPage/TeamSettingsPage.tsx, src/components/UserMembershipsList/UserMembershipsList.tsx, src/modules/groupMethods.ts, src/modules/groupSchemas.ts, src/trpc/router/groupRouter.ts
=> "Add team" button accessability

prisma/migrations/20240607153958_remove_edit_administrated_group_tree/migration.sql, prisma/schema.prisma, prisma/seed.ts, src/components/PageHeader/PageHeader.i18n/en.json, src/components/PageHeader/PageHeader.i18n/ru.json, src/components/PageHeader/PageHeader.tsx, src/components/PageHeaderActionButton/PageHeaderActionButton.tsx, src/trpc/router/groupRouter.ts, src/utils/access.ts
Resolve #847 
https://github.com/taskany-inc/crew/assets/9020793/65c299a2-6992-42a4-9f68-fe5fc85fab2c
=> Remove editAdministratedGroupTree flag

src/modules/scheduledDeactivationMethods.ts
=> Handle errors on scheduled deactivations operations

package-lock.json, src/modules/userMethods.ts
=>  Do not send excess properties in externalUserCreate

src/components/UserPage/UserPage.tsx
=> Fix nullable organization and role in user profile

src/components/AddAchievementModal/AddAchievementModal.tsx, src/modules/achievementMethods.ts, src/modules/modules.i18n/en.json, src/modules/modules.i18n/ru.json
=> Add nomination to notification email

src/components/GroupAdmins/GroupAdmins.tsx
Resolve #888 
https://github.com/taskany-inc/crew/assets/9020793/fa993a62-8f70-4f95-81ad-b2d3fae6dc00
=> Group Supervisor can't change admin list

src/components/AttachItem/AttachItem.tsx, src/components/ScheduleDeactivationForm/ScheduleDeactivationForm.tsx, src/modules/attachHooks.ts, src/trpc/router/attachRouter.ts, src/trpc/router/index.ts
=> Removing attachment through trpc router

src/components/AttachItem/AttachItem.tsx, src/components/ScheduleDeactivationForm/ScheduleDeactivationForm.tsx
=> Fix deleting files on scheduled deactivation form

src/config.ts, src/modules/scheduledDeactivationMethods.ts, src/modules/userMethods.ts, src/modules/userTypes.ts
=> Use mailing lists in scheduled deactivations

src/modules/userSchemas.ts
=> Add name/email field to Crew User

src/components/MembershipUserListItemEditable.tsx, src/modules/groupMethods.ts, src/modules/userMethods.ts, src/modules/userTypes.ts
=> Add organization to lists

src/components/BonusPointsBalanceModal/BonusPointsBalanceModal.tsx, src/modules/bonusPointsMethods.ts, src/modules/bonusPointsTypes.ts
=> Unavailable bonus points achivements cause client side exception

src/modules/userMethods.ts
=> Use HTTP 400 for errors with messages for users

src/components/PageHeader/PageHeader.i18n/en.json, src/components/PageHeader/PageHeader.i18n/ru.json, src/components/PageHeader/PageHeader.tsx, src/components/ProfilesManagementLayout/ProfilesManagementLayout.i18n/en.json, src/components/ProfilesManagementLayout/ProfilesManagementLayout.i18n/index.ts, src/components/ProfilesManagementLayout/ProfilesManagementLayout.i18n/ru.json, src/components/ProfilesManagementLayout/ProfilesManagementLayout.tsx, src/components/ScheduledDeactivationList/ScheduledDeactivationList.tsx, src/components/TabsLayout.tsx, src/components/UserCreateRequestsPage/UserCreateRequestsPage.tsx
=> Scheduled deactivations and create request on same place with tabs

src/components/UserPage/UserPage.i18n/en.json, src/components/UserPage/UserPage.i18n/ru.json, src/components/UserPage/UserPage.tsx, src/modules/scheduledDeactivationTypes.ts, src/modules/userMethods.ts, src/modules/userTypes.ts
=> Scheduled deactivation mark on profile

prisma/migrations/20240628140712_teamlead_id_in_scheduled_deactivation/migration.sql, prisma/schema.prisma, src/components/ScheduleDeactivationForm/ScheduleDeactivationForm.tsx, src/modules/scheduledDeactivationSchemas.ts
=> TeamLead by UserCombobox in ScheduledDeactivationForm

src/modules/groupMethods.ts
=> Fix error in exporting team members

src/components/ScheduleDeactivationForm/ScheduleDeactivationForm.tsx, src/modules/scheduledDeactivationHooks.ts
=> Add user invalidation on scheduled deactivation operations

src/config.ts, src/trpc/router/restRouter.ts
=> Hire sections calculations for achievement

src/components/UserFilterApplied/UserFilterApplied.tsx, src/components/UsersPage/UsersPage.tsx, src/components/UsersPageFilterPanel/UsersPageFilterPanel.tsx, src/hooks/useUserListFilterUrlParams.ts, src/modules/userMethods.ts, src/modules/userSchemas.ts, src/modules/userTypes.ts
=> Use url params for user list filter

src/components/LogsPage/LogsPage.tsx
=> History record does not display acting subsystem name or api token description

prisma/migrations/20240708165230_user_work_start_date/migration.sql, prisma/schema.prisma, src/modules/userMethods.ts, src/utils/emailTemplates.ts
=> Don't send a meeting email when creating user with start date

prisma/seed.ts, src/components/HistoryRecord/HistoryRecord.tsx, src/components/LayoutMain.tsx, src/utils/auth.ts, src/utils/getFavicon.ts
=> History record for the first user login

src/components/UsersPageFilterPanel/UsersPageFilterPanel.tsx
=> Active user filter does not work

src/components/CreateUserModal/CreateUserModal.tsx, src/components/UserCreateRequestsTable/UserCreateRequestsTable.tsx, src/components/UserCreationRequestModal/UserCreationRequestModal.tsx, src/modules/externalUserMethods.ts, src/modules/externalUserTypes.ts, src/modules/userCreationRequestHooks.ts, src/modules/userCreationRequestMethods.ts, src/modules/userCreationRequestSchemas.ts, src/modules/userCreationRequestTypes.ts, src/modules/userHooks.ts, src/modules/userMethods.ts, src/modules/userSchemas.ts, src/modules/userTypes.ts, src/pages/requests/users/index.tsx, src/trpc/inferredTypes.ts, src/trpc/router/index.ts, src/trpc/router/userCreationRequestRouter.ts, src/trpc/router/userRouter.ts, src/utils/notifications/notificationsMap.ts
=> Move user creation requests to separate module

package-lock.json, package.json, src/modules/userCreationRequestMethods.ts
=> In scheduled employee instead of buddy, coordinator and recruiter writes supervisor

src/components/CreateUserCreationRequestBaseForm/CreateUserCreationRequestBaseForm.tsx, src/components/CreateUserCreationRequestExternalEmployeeForm/CreateUserCreationRequestExternalEmployeeForm.tsx, src/components/CreateUserCreationRequestInternalEmployeeForm/CreateUserCreationRequestInternalEmployeeForm.tsx, src/components/ScheduleDeactivationForm/ScheduleDeactivationForm.tsx, src/modules/userCreationRequestMethods.ts, src/modules/userCreationRequestSchemas.ts
=>  Bugs on user request forms

prisma/migrations/20240715140013_api_token_value/migration.sql, prisma/schema.prisma, src/components/CreateUserCreationRequestExternalEmployeeForm/CreateUserCreationRequestExternalEmployeeForm.tsx, src/trpc/trpcBackend.ts
=> Api token model should have separate fields for id and token value

src/components/CreateUserCreationRequestExternalEmployeeForm/CreateUserCreationRequestExternalEmployeeForm.tsx, src/components/ScheduleDeactivationForm/ScheduleDeactivationForm.tsx, src/components/UserCreationRequestModal/UserCreationRequestModal.i18n/en.json, src/components/UserCreationRequestModal/UserCreationRequestModal.i18n/ru.json, src/components/UserCreationRequestModal/UserCreationRequestModal.tsx, src/utils/attachFormatter.ts
=> Comment to user request not visible in resolve modal

src/modules/userCreationRequestSchemas.ts
=> Supervisor and group should be obligatory in base user request schema

src/components/CreateUserModal/CreateUserModal.i18n/en.json, src/components/CreateUserModal/CreateUserModal.i18n/ru.json, src/components/CreateUserModal/CreateUserModal.tsx
=> Rename regular users to existing

src/components/ProfilesManagementLayout/ProfilesManagementLayout.i18n/en.json, src/components/ProfilesManagementLayout/ProfilesManagementLayout.i18n/ru.json, src/components/ProfilesManagementLayout/ProfilesManagementLayout.tsx, src/components/UserCreateRequestsTable/UserCreateRequestsTable.tsx, src/components/UserCreationRequestItem/UserCreationRequestItem.i18n/en.json, src/components/UserCreationRequestItem/UserCreationRequestItem.i18n/index.ts, src/components/UserCreationRequestItem/UserCreationRequestItem.i18n/ru.json, src/components/UserCreationRequestItem/UserCreationRequestItem.module.css, src/components/UserCreationRequestItem/UserCreationRequestItem.tsx, src/components/UserCreationRequestList/UserCreationRequestList.tsx, src/hooks/useRouter.ts, src/modules/userCreationRequestMethods.ts, src/modules/userCreationRequestSchemas.ts, src/pages/requests/list.tsx, src/trpc/router/userCreationRequestRouter.ts
=> Allow editing planned new users

src/components/CreateUserCreationRequestBaseForm/CreateUserCreationRequestBaseForm.i18n/en.json, src/components/CreateUserCreationRequestBaseForm/CreateUserCreationRequestBaseForm.i18n/ru.json, src/components/CreateUserCreationRequestBaseForm/CreateUserCreationRequestBaseForm.tsx, src/components/CreateUserCreationRequestExternalEmployeeForm/CreateUserCreationRequestExternalEmployeeForm.i18n/en.json, src/components/CreateUserCreationRequestExternalEmployeeForm/CreateUserCreationRequestExternalEmployeeForm.i18n/ru.json, src/components/CreateUserCreationRequestExternalEmployeeForm/CreateUserCreationRequestExternalEmployeeForm.tsx, src/components/CreateUserCreationRequestInternalEmployeeForm/CreateUserCreationRequestInternalEmployeeForm.i18n/en.json, src/components/CreateUserCreationRequestInternalEmployeeForm/CreateUserCreationRequestInternalEmployeeForm.i18n/ru.json, src/components/CreateUserCreationRequestInternalEmployeeForm/CreateUserCreationRequestInternalEmployeeForm.tsx, src/modules/modules.i18n/en.json, src/modules/modules.i18n/ru.json, src/modules/userCreationRequestMethods.ts, src/modules/userMethods.ts, src/trpc/router/userRouter.ts
=> Login should be unique in user requests

src/components/AdminPanel/AdminPanel.tsx, src/components/CreateUserCreationRequestInternalEmployeeForm/CreateUserCreationRequestInternalEmployeeForm.i18n/en.json, src/components/CreateUserCreationRequestInternalEmployeeForm/CreateUserCreationRequestInternalEmployeeForm.i18n/ru.json, src/components/HistoryRecord/HistoryRecord.i18n/en.json, src/components/HistoryRecord/HistoryRecord.i18n/ru.json, src/components/HistoryRecord/HistoryRecord.tsx, src/modules/historyEventTypes.ts, src/modules/userRoleHooks.ts, src/modules/userRoleMethods.ts, src/modules/userRoleSchemas.ts, src/trpc/router/groupRouter.ts, src/trpc/router/userRoleRouter.ts, src/trpc/router/userRouter.ts, src/utils/notifications/notificationsMap.ts
=>  History records for editUserRole, editMailingSettings, changeRoleScope

prisma/migrations/20240722153452_user_creation_request_creator/migration.sql, prisma/schema.prisma, src/modules/userCreationRequestMethods.ts, src/modules/userMethods.ts, src/trpc/router/userCreationRequestRouter.ts
=> Add author to the mailing list when scheduling new user

src/components/CreateUserCreationRequestInternalEmployeeForm/CreateUserCreationRequestInternalEmployeeForm.i18n/en.json, src/components/MailingList/MailingList.i18n/en.json, src/components/MailingList/MailingList.i18n/ru.json, src/components/MailingList/MailingList.tsx, src/components/UserPage/UserPage.i18n/en.json, src/components/UserPage/UserPage.i18n/ru.json, src/components/UserPage/UserPage.tsx, src/modules/deviceMethods.ts, src/modules/groupMethods.ts, src/modules/modules.i18n/en.json, src/modules/modules.i18n/ru.json, src/modules/serviceMethods.ts
=> Show readable error on unique constraint fails in SQL

src/utils/emailTemplates.ts, src/utils/utils.i18n/en.json, src/utils/utils.i18n/ru.json
=> Fix email layout

src/components/CreateUserCreationRequestBaseForm/CreateUserCreationRequestBaseForm.tsx, src/components/CreateUserCreationRequestExternalEmployeeForm/CreateUserCreationRequestExternalEmployeeForm.tsx, src/components/CreateUserCreationRequestInternalEmployeeForm/CreateUserCreationRequestInternalEmployeeForm.tsx
Resolve #1016 
https://github.com/user-attachments/assets/51429e7a-5002-4fb7-a321-9e83411d73a2
=> Don`t work monaco editor when create any user

src/modules/userCreationRequestMethods.ts
=> Fix supplemental positions on request resolve

src/components/TableCellText/TableCellText.module.css, src/components/TableCellText/TableCellText.tsx, src/components/TableListItem/TableListItem.module.css, src/components/UserCreateRequestsTable/UserCreateRequestTable.module.css, src/components/UserCreateRequestsTable/UserCreateRequestsTable.tsx
=> Profiles management: table markup issues

src/modules/scheduledDeactivationMethods.ts, src/modules/userCreationRequestMethods.ts, src/modules/userMethods.ts, src/trpc/router/userCreationRequestRouter.ts
=> Add teamlead to scheduled deactivation mail

src/components/UserPage/UserPage.tsx, src/modules/scheduledDeactivationMethods.ts, src/utils/scheduledDeactivationAllowed.ts
=>  Don't allow to schedule multiple deactivations per user

src/components/TeamPeople/TeamPeople.tsx, src/modules/groupMethods.ts, src/modules/modules.i18n/en.json, src/modules/modules.i18n/ru.json, src/modules/modules.test.ts
=> Add organizations to export

src/modules/groupMethods.ts
=> Fix undefined organization in group csv export

src/components/TeamSettingsPage/TeamSettingsPage.tsx, src/modules/groupSchemas.ts
=> Don't allow to rename group to empty string

src/utils/worker/jobOperations.ts
=> Worker doesn't find next job

src/components/UserUpdateForm/UserUpdateForm.tsx
=> Cannot delete user supervisor

src/components/EditPercentageForm/EditPercentageForm.tsx, src/modules/userMethods.ts
=> Available membership percentage should use current membership value

src/modules/achievementMethods.ts
=> Incorrect amount of bonuses on multiple sections update

src/modules/userMethods.ts
=> Remove role check in user request form

src/config.ts, src/modules/externalUserMethods.ts, src/pages/api/info.ts
=> Don't throw errors on integrations on test envs

src/components/AddAchievementModal/AddAchievementModal.tsx
=> Not all achievements shown

prisma/migrations/20240916104452_deactivation_request_work_place/migration.sql, prisma/schema.prisma, src/components/CreateUserCreationRequestInternalEmployeeForm/CreateUserCreationRequestInternalEmployeeForm.tsx, src/components/HistoryRecord/HistoryRecord.i18n/en.json, src/components/HistoryRecord/HistoryRecord.i18n/ru.json, src/components/HistoryRecord/HistoryRecord.tsx, src/components/ScheduleDeactivationForm/ScheduleDeactivationForm.i18n/en.json, src/components/ScheduleDeactivationForm/ScheduleDeactivationForm.i18n/ru.json, src/components/ScheduleDeactivationForm/ScheduleDeactivationForm.tsx, src/generated/kyselyTypes.ts, src/modules/historyEventTypes.ts, src/modules/modules.i18n/en.json, src/modules/modules.i18n/ru.json, src/modules/scheduledDeactivationMethods.ts, src/modules/scheduledDeactivationSchemas.ts, src/utils/emailTemplates.ts, src/utils/scheduledDeactivationHistoryEvent.ts
=> Deactivation form updates

package-lock.json, package.json, src/components/CreateUserCreationRequestBaseForm/CreateUserCreationRequestBaseForm.i18n/en.json, src/components/CreateUserCreationRequestBaseForm/CreateUserCreationRequestBaseForm.i18n/ru.json, src/components/CreateUserCreationRequestBaseForm/CreateUserCreationRequestBaseForm.module.css, src/components/CreateUserCreationRequestBaseForm/CreateUserCreationRequestBaseForm.tsx, src/components/CreateUserCreationRequestExternalEmployeeForm/CreateUserCreationRequestExternalEmployeeForm.i18n/en.json, src/components/CreateUserCreationRequestExternalEmployeeForm/CreateUserCreationRequestExternalEmployeeForm.i18n/ru.json, src/components/CreateUserCreationRequestExternalEmployeeForm/CreateUserCreationRequestExternalEmployeeForm.module.css, src/components/CreateUserCreationRequestExternalEmployeeForm/CreateUserCreationRequestExternalEmployeeForm.tsx, src/components/CreateUserCreationRequestInternalEmployeeForm/CreateUserCreationRequestInternalEmployeeForm.i18n/en.json, src/components/CreateUserCreationRequestInternalEmployeeForm/CreateUserCreationRequestInternalEmployeeForm.i18n/ru.json, src/components/CreateUserCreationRequestInternalEmployeeForm/CreateUserCreationRequestInternalEmployeeForm.module.css, src/components/CreateUserCreationRequestInternalEmployeeForm/CreateUserCreationRequestInternalEmployeeForm.tsx, src/utils/createUserCreationRequest.ts
=> Crew auto login in user creation request

src/components/UserCreationRequestModal/UserCreationRequestModal.i18n/en.json, src/components/UserCreationRequestModal/UserCreationRequestModal.i18n/ru.json, src/components/UserCreationRequestModal/UserCreationRequestModal.tsx, src/modules/userCreationRequestMethods.ts, src/modules/userCreationRequestTypes.ts
=> Add author of request to UserCreationRequestModal

prisma/migrations/20240924142106_optional_personal_mail_in_user_request/migration.sql, prisma/schema.prisma, src/components/CreateUserCreationRequestInternalEmployeeForm/CreateUserCreationRequestInternalEmployeeForm.tsx, src/components/HistoryRecord/HistoryRecord.i18n/en.json, src/components/HistoryRecord/HistoryRecord.i18n/ru.json, src/components/HistoryRecord/HistoryRecord.tsx, src/components/UserCreationRequestModal/UserCreationRequestModal.i18n/en.json, src/components/UserCreationRequestModal/UserCreationRequestModal.i18n/ru.json, src/components/UserCreationRequestModal/UserCreationRequestModal.tsx, src/generated/kyselyTypes.ts, src/modules/historyEventTypes.ts, src/modules/userCreationRequestMethods.ts, src/modules/userCreationRequestSchemas.ts, src/trpc/router/userCreationRequestRouter.ts
=> Optional personal email in internal user creation request

src/components/CreateUserCreationRequestInternalEmployeeForm/CreateUserCreationRequestInternalEmployeeForm.tsx
=> Fix email change on user creation request

src/modules/userMethods.ts
=> User achievements should be visible unless they are explicitly hidden in the settings

package-lock.json, package.json
=> UserComboboxs Input does't autofocuses

prisma/migrations/20240930200603_multiple_user_names/migration.sql, prisma/schema.prisma, src/components/HistoryRecord/HistoryRecord.i18n/en.json, src/components/HistoryRecord/HistoryRecord.i18n/ru.json, src/components/HistoryRecord/HistoryRecord.tsx, src/components/UserPage/UserPage.i18n/en.json, src/components/UserPage/UserPage.i18n/ru.json, src/components/UserPage/UserPage.tsx, src/components/UserUpdateForm/UserUpdateForm.i18n/en.json, src/components/UserUpdateForm/UserUpdateForm.i18n/ru.json, src/components/UserUpdateForm/UserUpdateForm.tsx, src/generated/kyselyTypes.ts, src/modules/historyEventTypes.ts, src/modules/userMethods.ts, src/modules/userSchemas.ts, src/modules/userTypes.ts, src/trpc/router/restRouter.ts, src/trpc/router/userRouter.ts
=> Alternate user names field

src/components/CreateUserCreationRequestInternalEmployeeForm/CreateUserCreationRequestInternalEmployeeForm.tsx, src/components/UserComboBox/UserComboBox.tsx
=> Cannot change selected user in UserComboBox

src/middleware.ts, src/trpc/router/groupRouter.ts, src/trpc/router/searchRouter.ts, src/trpc/router/userCreationRequestRouter.ts, src/trpc/router/userRouter.ts, src/utils/analyticsEvent.ts
=> Telemetry: user actions

prisma/migrations/20241010153034_optional_group_in_user_creation_request/migration.sql, prisma/schema.prisma, src/components/GroupComboBox/GroupComboBox.tsx, src/components/InternalUserCreationRequestPage/InternalUserCreationRequestPage.tsx, src/components/UserCreateRequestsTable/UserCreateRequestsTable.tsx, src/components/UserCreationRequestModal/UserCreationRequestModal.tsx, src/generated/kyselyTypes.ts, src/modules/historyEventTypes.ts, src/modules/userCreationRequestMethods.ts, src/modules/userCreationRequestSchemas.ts, src/modules/userCreationRequestTypes.ts, src/modules/userMethods.ts, src/trpc/router/userCreationRequestRouter.ts, src/utils/emailTemplates.ts, src/utils/utils.i18n/en.json, src/utils/utils.i18n/ru.json
=> Optional team for internal newcomer request

src/components/InternalUserCreationRequestPage/InternalUserCreationRequestPage.module.css, src/components/InternalUserCreationRequestPage/InternalUserCreationRequestPage.tsx, src/components/NavItem/NavItem.module.css, src/components/NavItem/NavItem.tsx, src/components/NavMenu/NavMenu.module.css, src/components/NavMenu/NavMenu.tsx
https://github.com/user-attachments/assets/53a615b1-2c78-4e60-bce6-1ce375f89e10
=> feat(INTERNAL-1193): nav menu for form

src/components/InternalUserCreationRequestPage/InternalUserCreationRequestPage.tsx
=> Do not immediately trigger empty login

package-lock.json, package.json, src/components/InternalUserCreationRequestPage/InternalUserCreationRequestPage.tsx, src/modules/userCreationRequestSchemas.ts
=> Phone validation

src/components/InternalUserCreationRequestPage/InternalUserCreationRequestPage.module.css, src/components/InternalUserCreationRequestPage/InternalUserCreationRequestPage.tsx, src/components/NavItem/NavItem.tsx, src/components/NavMenu/NavMenu.tsx, src/hooks/useSpyNav.ts
https://github.com/user-attachments/assets/6ef33ec8-83f6-4ac5-b6b3-26cf9cee43aa
=> feat(INTERNAL-1254): spy nav on scroll

src/modules/achievementMethods.ts, src/modules/modules.i18n/en.json, src/modules/modules.i18n/ru.json, src/modules/scheduledDeactivationMethods.ts
=> Add a link to the service in all notifications

src/utils/emailTemplates.ts, src/utils/utils.i18n/ru.json
=> Not printing null comments

src/middleware.ts, src/trpc/router/groupRouter.ts, src/trpc/router/searchRouter.ts, src/trpc/router/userCreationRequestRouter.ts, src/trpc/router/userRouter.ts, src/utils/analyticsEvent.ts
Fixed a bug when telemetry logged next/_data events + added parsed searchparams to pageviews
=> Telemetry fixes

src/modules/userCreationRequestMethods.ts
=> Fix groupId in creation user request

src/components/CreateUserCreationRequestBaseForm/CreateUserCreationRequestBaseForm.tsx, src/components/CreateUserCreationRequestExternalEmployeeForm/CreateUserCreationRequestExternalEmployeeForm.tsx, src/components/ExternalFromMainOrgUserCreationRequestPage/ExternalFromMainOrgUserCreationRequestPage.tsx, src/components/InternalUserCreationRequestPage/InternalUserCreationRequestPage.tsx, src/modules/userCreationRequestSchemas.ts
=> Fix translation errors

src/components/CreateUserModal/CreateUserModal.i18n/en.json, src/components/CreateUserModal/CreateUserModal.i18n/ru.json, src/components/CreateUserModal/CreateUserModal.module.css, src/components/CreateUserModal/CreateUserModal.tsx, src/hooks/useRouter.ts
=> Modal to user request forms

prisma/migrations/20241030174431_personnel_number_in_org/migration.sql, prisma/schema.prisma, src/generated/kyselyTypes.ts
=> Personnel number in organization

src/modules/userCreationRequestMethods.ts
=> Accept profile for existing user request immediately

src/components/AddSupplementalPosition/AddSupplementalPosition.tsx, src/components/ExternalFromMainOrgUserCreationRequestPage/ExternalFromMainOrgUserCreationRequestPage.module.css, src/components/ExternalFromMainOrgUserCreationRequestPage/ExternalFromMainOrgUserCreationRequestPage.tsx, src/components/ExternalUserCreationRequestPage/ExternalUserCreationRequestPage.tsx, src/components/UserFormExternalExtraInfoBlock/UserFormExternalExtraInfoBlock.module.css, src/components/UserFormExternalExtraInfoBlock/UserFormExternalExtraInfoBlock.tsx, src/components/UserFormExternalTeamBlock/UserFormExternalTeamBlock.module.css, src/components/UserFormExternalTeamBlock/UserFormExternalTeamBlock.tsx, src/components/UserFormPersonalDataBlock/UserFormPersonalDataBlock.i18n/en.json, src/components/UserFormPersonalDataBlock/UserFormPersonalDataBlock.i18n/ru.json, src/components/UserFormPersonalDataBlock/UserFormPersonalDataBlock.tsx, src/components/UserFormRegistrationBlock/UserFormRegistrationBlock.module.css, src/components/UserFormRegistrationBlock/UserFormRegistrationBlock.tsx, src/components/UserFormTeamBlock/UserFormTeamBlock.tsx
=> Make inputs narrower

prisma/migrations/20241031101118_position/migration.sql, prisma/schema.prisma, src/generated/kyselyTypes.ts, src/modules/userCreationRequestMethods.ts, src/modules/userMethods.ts
=> New format for user supplementalPositions

prisma/migrations/20241106222555_personnel_number_to_string/migration.sql, prisma/schema.prisma, src/generated/kyselyTypes.ts
=> Change personnel number from int to string

src/components/ExternalUserCreationRequestPage/ExternalUserCreationRequestPage.tsx, src/components/UserFormExternalExtraInfoBlock/UserFormExternalExtraInfoBlock.module.css, src/components/UserFormExternalExtraInfoBlock/UserFormExternalExtraInfoBlock.tsx, src/modules/attachMethods.ts, src/modules/userCreationRequestMethods.ts
=> Attaches in readonly external user request

src/components/ExternalFromMainOrgUserCreationRequestPage/ExternalFromMainOrgUserCreationRequestPage.tsx, src/modules/userCreationRequestMethods.ts, src/pages/requests/users/external-from-main/[requestId]/index.tsx, src/trpc/router/userCreationRequestRouter.ts, src/utils/types.ts
=> Readonly for request external user from main page

src/components/AddSupplementalPosition/AddSupplementalPosition.i18n/en.json, src/components/AddSupplementalPosition/AddSupplementalPosition.i18n/ru.json, src/components/AddSupplementalPosition/AddSupplementalPosition.tsx, src/components/DecideOnRequestFormActions/DecideOnRequestFormActions.i18n/en.json, src/components/DecideOnRequestFormActions/DecideOnRequestFormActions.i18n/ru.json, src/components/DecideOnRequestFormActions/DecideOnRequestFormActions.tsx, src/components/GroupComboBox/GroupComboBox.tsx, src/components/InternalUserCreationRequestPage/InternalUserCreationRequestPage.i18n/en.json, src/components/InternalUserCreationRequestPage/InternalUserCreationRequestPage.i18n/ru.json, src/components/InternalUserCreationRequestPage/InternalUserCreationRequestPage.tsx, src/components/RoleSelect/RoleSelect.tsx, src/components/UserFormCommentsBlock/UserFormCommentsBlock.tsx, src/components/UserFormFormActions/UserFormFormActions.tsx, src/components/UserFormPersonalDataBlock/UserFormPersonalDataBlock.tsx, src/components/UserFormRegistrationBlock/UserFormRegistrationBlock.i18n/en.json, src/components/UserFormRegistrationBlock/UserFormRegistrationBlock.i18n/ru.json, src/components/UserFormRegistrationBlock/UserFormRegistrationBlock.tsx, src/components/UserFormTeamBlock/UserFormTeamBlock.tsx, src/components/UserFormWorkSpaceBlock/UserFormWorkSpaceBlock.i18n/en.json, src/components/UserFormWorkSpaceBlock/UserFormWorkSpaceBlock.i18n/ru.json, src/components/UserFormWorkSpaceBlock/UserFormWorkSpaceBlock.tsx, src/components/UserSelect/UserSelect.tsx, src/components/WarningModal/WarningModal.tsx, src/components/WorkModeCombobox/WorkModeCombobox.tsx, src/hooks/useRouter.ts, src/modules/userCreationRequestMethods.ts, src/pages/requests/users/internal/[requestId]/index.tsx, src/trpc/router/userCreationRequestRouter.ts
=> Request for scheduled employee exit in reading "read only"

src/components/UserPage/UserPage.tsx
=> Show main position at user page

src/components/ParseTeamStructurePage/ParseTeamStructurePage.tsx, src/components/UploadTeamStructurePage/UploadTeamStructurePage.i18n/en.json, src/components/UploadTeamStructurePage/UploadTeamStructurePage.i18n/ru.json, src/components/UploadTeamStructurePage/UploadTeamStructurePage.module.css, src/components/UploadTeamStructurePage/UploadTeamStructurePage.tsx, src/modules/importMethods.ts, src/trpc/router/importRouter.ts, src/trpc/router/index.ts
=> Backend part of uploading parsed structure

src/modules/userCreationRequestMethods.ts
=> Supplemental position creation

src/config.ts
=> Flag for mailer

src/components/ParseTeamStructurePage/ParseTeamStructurePage.tsx
=> Fix ParseTeamStructurePage, callback with filtered value

src/modules/importMethods.ts, src/utils/commandLine.ts, src/utils/dump.ts, src/utils/regex.ts
=> Regex name search in parsing methods

src/modules/userCreationRequestMethods.ts, src/modules/userMethods.ts
=> Current date for external from main request

package-lock.json, package.json, src/components/DecreeForm/DecreeForm.i18n/en.json, src/components/DecreeForm/DecreeForm.i18n/ru.json, src/components/DecreeForm/DecreeForm.tsx, src/components/RequestFormActions/RequestFormActions.tsx, src/components/UserDecreeRequestsPage/UserDecreeRequestsPage.i18n/en.json, src/components/UserDecreeRequestsPage/UserDecreeRequestsPage.i18n/ru.json, src/components/UserDecreeRequestsPage/UserDecreeRequestsPage.tsx, src/components/UserFormWorkSpaceBlock/UserFormWorkSpaceBlock.i18n/en.json, src/components/UserFormWorkSpaceBlock/UserFormWorkSpaceBlock.i18n/ru.json, src/components/UserFormWorkSpaceBlock/UserFormWorkSpaceBlock.tsx, src/components/UserPage/UserPage.tsx, src/modules/modules.i18n/en.json, src/modules/modules.i18n/ru.json, src/modules/nodemailer.ts, src/modules/scheduledDeactivationMethods.ts, src/modules/userCreationRequestMethods.ts, src/modules/userCreationRequestSchemas.ts, src/modules/userMethods.ts, src/pages/requests/users/decree/from/[userId].tsx, src/pages/requests/users/decree/to/[userId].tsx, src/utils/emailTemplates.ts, src/utils/supplementalPositions.ts, src/utils/utils.i18n/en.json, src/utils/utils.i18n/ru.json, src/worker/create.ts
https://github.com/user-attachments/assets/ffc955bb-4584-4d4d-886d-d760579be6a2
=> Decrees: additional fields

src/modules/userMethods.ts, src/worker/resolve.ts
=> Еmail for external service

prisma/migrations/20241127122901_add_curators_in_user_profile/migration.sql, prisma/schema.prisma, src/components/UserPage/UserPage.tsx, src/components/UserSelect/UserSelect.tsx, src/components/UserSummary/UserSummary.i18n/en.json, src/components/UserSummary/UserSummary.i18n/ru.json, src/components/UserSummary/UserSummary.tsx, src/components/UserUpdateForm/UserUpdateForm.i18n/en.json, src/components/UserUpdateForm/UserUpdateForm.i18n/ru.json, src/components/UserUpdateForm/UserUpdateForm.module.css, src/components/UserUpdateForm/UserUpdateForm.tsx, src/generated/kyselyTypes.ts, src/modules/userMethods.ts, src/modules/userSchemas.ts, src/modules/userTypes.ts, src/trpc/router/userRouter.ts, src/utils/calculateDiffBetweenArrays.ts
=> Add a curator to profile

src/components/AccessCoordinationList/AccessCoordinationList.tsx, src/components/ScheduledDeactivationList/ScheduledDeactivationList.i18n/en.json, src/components/ScheduledDeactivationList/ScheduledDeactivationList.tsx, src/components/UserCreateRequestsPage/UserCreateRequestsPage.tsx, src/components/UserDecreeRequestsPage/UserDecreeRequestsPage.tsx
=> Tooltip in table header does not crop

src/components/ExistingUserCreationRequestPage/ExistingUserCreationRequestPage.tsx
=> fix(INTERNAL-1095): fix readonly fields

src/components/UserSettingsPage/UserSettingsPage.i18n/en.json, src/components/UserSettingsPage/UserSettingsPage.i18n/ru.json, src/components/UserSettingsPage/UserSettingsPage.module.css, src/components/UserSettingsPage/UserSettingsPage.tsx
=> Sign-out button

prisma/migrations/20241129152721_emails_in_mailin_settings/migration.sql, prisma/schema.prisma, src/components/HistoryRecord/HistoryRecord.i18n/en.json, src/components/HistoryRecord/HistoryRecord.i18n/ru.json, src/components/HistoryRecord/HistoryRecord.tsx, src/components/MailingList/MailingList.i18n/en.json, src/components/MailingList/MailingList.i18n/ru.json, src/components/MailingList/MailingList.module.css, src/components/MailingList/MailingList.tsx, src/components/MailingLists/MailingLists.tsx, src/generated/kyselyTypes.ts, src/modules/historyEventTypes.ts, src/modules/mailSettingsHooks.ts, src/modules/mailSettingsMethods.ts, src/modules/mailingSettingsSchemas.ts, src/modules/userMethods.ts, src/trpc/router/index.ts, src/trpc/router/mailingSettingsRouter.ts, src/trpc/router/userRouter.ts, src/utils/regex.ts
=> Additional emails for mailing settings

src/utils/getActiveScheduledDeactivation.ts
=> Fix visibility deactivation date

src/components/ScheduleDeactivationForm/ScheduleDeactivationForm.tsx
=> Fix test devices and comments in deactivation form

src/components/ScheduledDeactivationEditMenu/ScheduledDeactivationEditMenu.tsx, src/components/ScheduledDeactivationList/ScheduledDeactivationList.tsx
=> Open edit and cancel deactivation modal in deactivation list

src/components/ScheduleDeactivationForm/ScheduleDeactivationForm.tsx, src/components/WorkModeCombobox/WorkModeCombobox.tsx
=> WorkModeCombobox in ScheduleDeactivationForm

src/components/ParseTeamStructurePage/ParseTeamStructurePage.i18n/en.json, src/components/ParseTeamStructurePage/ParseTeamStructurePage.i18n/ru.json, src/components/ParseTeamStructurePage/ParseTeamStructurePage.tsx, src/modules/importMethods.ts, src/modules/importSchemas.ts, src/modules/nodemailer.ts, src/utils/auth.ts
=> Structure parsing: source column

src/components/DecreeForm/DecreeForm.tsx, src/components/HistoryRecord/HistoryRecord.i18n/en.json, src/components/HistoryRecord/HistoryRecord.i18n/ru.json, src/components/HistoryRecord/HistoryRecord.tsx, src/components/UserPage/UserPage.tsx, src/modules/historyEventTypes.ts, src/modules/userCreationRequestHooks.ts, src/modules/userCreationRequestMethods.ts, src/trpc/router/userCreationRequestRouter.ts, src/worker/resolve.ts
=> Decree logs

prisma/migrations/20241204162245_org_group_id_in_app_config/migration.sql, prisma/schema.prisma, prisma/seed.ts, src/components/HistoryRecord/HistoryRecord.tsx, src/components/LayoutMain/LayoutMain.tsx, src/components/OrganizationUserGroupSwitch/OrganizationUserGroupSwitch.tsx, src/components/PageHeader/PageHeader.tsx, src/components/TeamPageHeader/TeamPageHeader.tsx, src/components/TeamsPage/TeamsPage.tsx, src/config.ts, src/contexts/appConfigContext.tsx, src/generated/kyselyTypes.ts, src/pages/_app.tsx, src/trpc/inferredTypes.ts, src/utils/getFavicon.ts
=> Store org group id in app config table

src/components/AccessCoordinationList/AccessCoordinationList.tsx, src/components/ProfilesManagementLayout/ProfilesManagementLayout.i18n/en.json, src/components/ProfilesManagementLayout/ProfilesManagementLayout.i18n/ru.json, src/components/ProfilesManagementLayout/ProfilesManagementLayout.tsx, src/components/ScheduledDeactivationList/ScheduledDeactivationList.tsx, src/components/UserCreateRequestsPage/UserCreateRequestsPage.tsx, src/components/UserDecreeRequestsPage/UserDecreeRequestsPage.tsx, src/modules/scheduledDeactivationMethods.ts, src/modules/scheduledDeactivationSchemas.ts
=> Add search by name

src/components/ProfilesManagementLayout/ProfilesManagementLayout.tsx, src/components/SearchFilter.tsx, src/modules/scheduledDeactivationMethods.ts
=> Tabs don`t work in profile managments 

prisma/migrations/20241209145327_decree_disable_account/migration.sql, prisma/schema.prisma, src/components/DecreeForm/DecreeForm.tsx, src/components/DecreePage/DecreePage.tsx, src/components/UserFormPersonalDataBlock/UserFormPersonalDataBlock.i18n/en.json, src/components/UserFormPersonalDataBlock/UserFormPersonalDataBlock.i18n/ru.json, src/components/UserFormPersonalDataBlock/UserFormPersonalDataBlock.module.css, src/components/UserFormPersonalDataBlock/UserFormPersonalDataBlock.tsx, src/modules/userCreationRequestMethods.ts, src/modules/userCreationRequestSchemas.ts, src/modules/userMethods.ts
=> Add disable account checkbox

src/components/DecreeForm/DecreeForm.tsx, src/generated/kyselyTypes.ts
=> Update decree form buttons

src/components/ScheduledDeactivationList/ScheduledDeactivationList.tsx
=> ScheduleDeactivationForm change id to userId

src/modules/modules.i18n/en.json, src/modules/modules.i18n/ru.json, src/modules/scheduledDeactivationMethods.ts, src/modules/userCreationRequestMethods.ts, src/utils/createUserCreationRequest.ts, src/utils/emailTemplates.ts, src/utils/utils.i18n/en.json, src/utils/utils.i18n/ru.json
=> Correct styles and texts

src/components/GroupComboBox/GroupComboBox.tsx, src/components/UserFormTeamBlock/UserFormTeamBlock.tsx, src/components/UserSelect/UserSelect.tsx, src/modules/groupMethods.ts, src/modules/groupSchemas.ts, src/trpc/router/groupRouter.ts
=> Default group from supervisor

src/modules/userMethods.ts
=> Edit user supervisor fix

src/components/UserFormWorkSpaceBlock/UserFormWorkSpaceBlock.i18n/ru.json, src/modules/userCreationRequestMethods.ts, src/trpc/router/userCreationRequestRouter.ts, src/utils/utils.i18n/ru.json
=> UnitId null in user profile

src/components/ExistingUserCreationRequestPage/ExistingUserCreationRequestPage.tsx, src/components/ExternalFromMainOrgUserCreationRequestPage/ExternalFromMainOrgUserCreationRequestPage.tsx, src/components/ExternalUserCreationRequestPage/ExternalUserCreationRequestPage.tsx, src/components/InternalUserCreationRequestPage/InternalUserCreationRequestPage.tsx, src/modules/userCreationRequestMethods.ts, src/modules/userCreationRequestSchemas.ts
=> Fix date clear in user creation requests

src/components/RequestFormActions/RequestFormActions.tsx
=> Fix action buttons

src/components/HistoryRecord/HistoryRecord.i18n/en.json, src/components/HistoryRecord/HistoryRecord.i18n/ru.json, src/components/HistoryRecord/HistoryRecord.tsx, src/modules/historyEventTypes.ts, src/modules/scheduledDeactivationMethods.ts, src/trpc/router/scheduledDeactivationRouter.ts
=> Remove devices from user removed in scheduled deactivation

src/components/RequestFormActions/RequestFormActions.tsx, src/components/UserFormCommentsBlock/UserFormCommentsBlock.i18n/en.json, src/components/UserFormCommentsBlock/UserFormCommentsBlock.i18n/ru.json, src/components/UserFormCommentsBlock/UserFormCommentsBlock.tsx, src/components/UserFormWorkSpaceBlock/UserFormWorkSpaceBlock.i18n/ru.json
=> Comments on the application form

src/components/UserFormTeamBlock/UserFormTeamBlock.tsx
https://github.com/user-attachments/assets/b9e23baf-613c-4d04-8110-c4380a758dab
=> Fix defaultGroup problem

src/modules/importMethods.ts, src/utils/csv.test.ts, src/utils/csv.ts
=> Extended structure parse report

src/components/ScheduledDismissalPage/ScheduledDismissalPage.tsx, src/components/UserFormTeamBlock/UserFormTeamBlock.tsx, src/modules/scheduledDeactivationMethods.ts, src/modules/scheduledDeactivationSchemas.ts, src/utils/emailTemplates.ts
=> Default group and mail text fixes

prisma/seed.ts, src/components/ScheduledDismissalPage/ScheduledDismissalPage.tsx, src/components/UserFormPersonalDataBlock/UserFormPersonalDataBlock.tsx, src/modules/scheduledDeactivationMethods.ts, src/modules/scheduledDeactivationSchemas.ts, src/modules/serviceMethods.ts, src/modules/userMethods.ts, src/pages/users/[userId]/dismiss/edit.tsx, src/pages/users/[userId]/dismiss/index.tsx, src/pages/users/[userId]/dismiss/new.tsx
=> Work and personal mails for user

src/components/GroupTreeViewNode/GroupTreeViewNode.module.css, src/components/GroupTreeViewNode/GroupTreeViewNode.tsx
=> fix(GroupTreeViewNode): fix supervisor position and background color

prisma/seed.ts, src/components/AccessCoordinationList/AccessCoordinationList.tsx, src/components/AddServiceToUserForm/AddServiceToUserForm.tsx, src/components/CreateDecreeForm/CreateDecreeForm.tsx, src/components/ScheduleDeactivationForm/ScheduleDeactivationForm.tsx, src/modules/scheduledDeactivationMethods.ts, src/modules/serviceSchemas.ts, src/modules/userCreationRequestMethods.ts, src/modules/userMethods.ts, src/pages/users/[userId]/dismiss/edit.tsx, src/pages/users/[userId]/dismiss/index.tsx, src/pages/users/[userId]/dismiss/new.tsx, src/trpc/router/restRouter.ts, src/utils/auth.ts, src/utils/createUserCreationRequest.ts, src/utils/externalServices.ts, src/worker/resolve.ts
=> Enum for external service names

src/trpc/router/userCreationRequestRouter.ts
=> Fix decree list request

src/components/UserPage/UserPage.tsx
=> Fix active display

src/modules/scheduledDeactivationMethods.ts
=> Fix deactivate date at edit bug

src/modules/scheduledDeactivationMethods.ts, src/modules/userCreationRequestMethods.ts, src/utils/emailTemplates.ts, src/utils/utils.i18n/en.json, src/utils/utils.i18n/ru.json, src/worker/resolve.ts
=> Mail subjects and texts fix

src/utils/emailTemplates.ts
=> New mail table templates

src/modules/groupMethods.ts
=> Get group tree filtered by supervisors on backend

prisma/migrations/20250128101921_workspace_mailing_settings/migration.sql, prisma/schema.prisma, src/components/HistoryRecord/HistoryRecord.i18n/en.json, src/components/HistoryRecord/HistoryRecord.i18n/ru.json, src/components/HistoryRecord/HistoryRecord.tsx, src/components/MailingList/MailingList.i18n/en.json, src/components/MailingList/MailingList.i18n/ru.json, src/components/MailingList/MailingList.tsx, src/generated/kyselyTypes.ts, src/modules/historyEventTypes.ts, src/modules/mailSettingsHooks.ts, src/modules/mailSettingsMethods.ts, src/modules/mailingSettingsSchemas.ts, src/modules/nodemailer.ts, src/modules/scheduledDeactivationMethods.ts, src/modules/userCreationRequestMethods.ts, src/modules/userMethods.ts, src/trpc/router/mailingSettingsRouter.ts, src/utils/analyticsEvent.ts
=> Workspace email in mailing settings

src/components/ExistingUserCreationRequestPage/ExistingUserCreationRequestPage.tsx, src/components/ExternalFromMainOrgUserCreationRequestPage/ExternalFromMainOrgUserCreationRequestPage.tsx, src/components/ExternalUserCreationRequestPage/ExternalUserCreationRequestPage.tsx, src/components/InternalUserCreationRequestPage/InternalUserCreationRequestPage.tsx, src/components/UserFormPersonalDataBlock/UserFormPersonalDataBlock.tsx, src/modules/userHooks.ts, src/utils/analyticsEvent.ts
=> New validation for emails and login in user request forms

src/components/AddSupplementalPosition/AddSupplementalPosition.i18n/en.json, src/components/AddSupplementalPosition/AddSupplementalPosition.i18n/ru.json, src/components/AddSupplementalPosition/AddSupplementalPosition.tsx, src/components/UserFormDevicesBlock/UserFormDevicesBlock.tsx, src/components/UserFormRegistrationBlock/UserFormRegistrationBlock.tsx, src/components/UserFormSupplementalPositionsBlock/UserFormSupplementalPositionsBlock.tsx, src/components/UserUpdateForm/UserUpdateForm.tsx, src/modules/userCreationRequestMethods.ts, src/modules/userCreationRequestSchemas.ts, src/utils/errorPicker.ts
=> workStartDate for supplemental position in user creation request

prisma/migrations/20250203213819_location_table/migration.sql, prisma/schema.prisma, src/components/CreateDecreeForm/CreateDecreeForm.tsx, src/components/ScheduleDeactivationForm/ScheduleDeactivationForm.tsx, src/components/ScheduledDismissalPage/ScheduledDismissalPage.tsx, src/components/UserPage/UserPage.tsx, src/components/UserSummary/UserSummary.i18n/en.json, src/components/UserSummary/UserSummary.i18n/ru.json, src/components/UserSummary/UserSummary.tsx, src/generated/kyselyTypes.ts, src/modules/locationMethods.ts, src/modules/locationTypes.ts, src/modules/userMethods.ts, src/modules/userTypes.ts
=> User location

src/components/ExternalFromMainOrgUserCreationRequestPage/ExternalFromMainOrgUserCreationRequestPage.tsx, src/components/ExternalUserCreationRequestPage/ExternalUserCreationRequestPage.tsx, src/components/InternalUserCreationRequestPage/InternalUserCreationRequestPage.tsx
=> Do not check on unique default login

src/modules/scheduledDeactivationMethods.ts
=> Throw error on creating deactivation if user has active one

src/components/TeamItem/TeamItem.tsx, src/components/TeamPage/TeamPage.tsx, src/components/TeamProfilePreview/TeamProfilePreview.tsx, src/components/TeamVacanciesV2/TeamVacancies.tsx, src/components/UserComboBox/UserComboBox.tsx, src/components/VacancyItem/VacancyItem.tsx, src/modules/groupMethods.ts, src/modules/vacancyTypes.ts, src/trpc/inferredTypes.ts, src/trpc/router/groupRouter.ts
=> vacancies from group and children and people counter

src/components/OrganizationUserGroupSwitch/OrganizationUserGroupSwitch.i18n/en.json, src/components/OrganizationUserGroupSwitch/OrganizationUserGroupSwitch.i18n/ru.json, src/components/OrganizationUserGroupSwitch/OrganizationUserGroupSwitch.tsx, src/components/TeamPageHeader/TeamPageHeader.i18n/en.json, src/components/TeamPageHeader/TeamPageHeader.i18n/ru.json, src/components/TeamPageHeader/TeamPageHeader.tsx
=> Tabs and texts

src/components/UserCreateRequestsPage/UserCreateRequestsPage.tsx, src/components/UserDecreeRequestsPage/UserDecreeRequestsPage.tsx
=> Show archived requests 

src/components/AccessCoordinationList/AccessCoordinationList.i18n/en.json, src/components/AccessCoordinationList/AccessCoordinationList.i18n/ru.json, src/components/AccessCoordinationList/AccessCoordinationList.tsx, src/components/RequestFormActions/RequestFormActions.i18n/ru.json, src/components/ScheduledDeactivationList/ScheduledDeactivationList.i18n/en.json, src/components/ScheduledDeactivationList/ScheduledDeactivationList.i18n/ru.json, src/components/ScheduledDeactivationList/ScheduledDeactivationList.tsx, src/components/UserCreateRequestsPage/UserCreateRequestsPage.i18n/en.json, src/components/UserCreateRequestsPage/UserCreateRequestsPage.i18n/ru.json, src/components/UserCreateRequestsPage/UserCreateRequestsPage.tsx, src/config.ts
=> Request types in lists

prisma/migrations/20250218145135_coordinator_ids_in_transfer/migration.sql, prisma/schema.prisma, src/components/HistoryRecord/HistoryRecord.tsx, src/components/ScheduledDismissalPage/ScheduledDismissalPage.i18n/en.json, src/components/ScheduledDismissalPage/ScheduledDismissalPage.i18n/ru.json, src/components/ScheduledDismissalPage/ScheduledDismissalPage.tsx, src/components/UserFormSupplementalPositionsBlock/UserFormSupplementalPositionsBlock.i18n/en.json, src/components/UserFormSupplementalPositionsBlock/UserFormSupplementalPositionsBlock.i18n/ru.json, src/components/UserFormSupplementalPositionsBlock/UserFormSupplementalPositionsBlock.tsx, src/components/UserFormTeamBlock/UserFormTeamBlock.tsx, src/generated/kyselyTypes.ts, src/modules/scheduledDeactivationMethods.ts, src/modules/scheduledDeactivationSchemas.ts, src/trpc/router/scheduledDeactivationRouter.ts, src/utils/analyticsEvent.ts, src/utils/emailTemplates.ts, src/utils/scheduledDeactivationHistoryEvent.ts, src/utils/utils.i18n/en.json, src/utils/utils.i18n/ru.json
=> Scheduled transfer edit and transfer history record

package-lock.json, src/components/AccessCoordinationList/AccessCoordinationList.module.css, src/components/AccessCoordinationList/AccessCoordinationList.tsx, src/components/RequestFormActions/RequestFormActions.tsx, src/components/ScheduledDeactivationEditMenu/ScheduledDeactivationEditMenu.tsx, src/components/ScheduledDeactivationList/ScheduledDeactivationList.module.css, src/components/ScheduledDeactivationList/ScheduledDeactivationList.tsx, src/components/UserCreateRequestsPage/UserCreateRequestsPage.module.css, src/components/UserCreateRequestsPage/UserCreateRequestsPage.tsx, src/components/UserDecreeRequestsPage/UserDecreeRequestsPage.module.css, src/components/UserDecreeRequestsPage/UserDecreeRequestsPage.tsx
=> Update DataTable component

src/modules/groupMethods.ts, src/trpc/router/groupRouter.ts
=> correct querying tree by groups

src/components/CorporateTeamsPage/CorporateTeamsPage.tsx, src/components/GroupTreeViewNode/GroupTreeViewNode.tsx, src/components/TeamsPage/TeamsPage.tsx, src/components/VirtualTeamsPage/VirtualTeamsPage.tsx, src/utils/sortByStringKey.ts
=> Add client tree sorting

prisma/migrations/20250220144501_buseness_unit_group/migration.sql, prisma/schema.prisma, src/components/CorporateTeamsPage/CorporateTeamsPage.tsx, src/components/CreateGroupModal/CreateGroupModal.i18n/en.json, src/components/CreateGroupModal/CreateGroupModal.i18n/ru.json, src/components/CreateGroupModal/CreateGroupModal.module.css, src/components/CreateGroupModal/CreateGroupModal.tsx, src/components/FormActions/FormActions.module.css, src/components/FormActions/FormActions.tsx, src/components/TeamSettingsPage/TeamSettingsPage.i18n/en.json, src/components/TeamSettingsPage/TeamSettingsPage.i18n/ru.json, src/components/TeamSettingsPage/TeamSettingsPage.tsx, src/components/TeamsPage/TeamsPage.tsx, src/components/VirtualTeamsPage/VirtualTeamsPage.tsx, src/generated/kyselyTypes.ts, src/modules/groupSchemas.ts
=> Business unit groups

src/trpc/router/serviceRouter.ts
=> Show user servises not to everyone

src/components/RequestFormActions/RequestFormActions.tsx
=> Edit requests enabled

src/components/TeamTreeLayoutWrapper/TeamTreeLayoutWrapper.tsx
=> Hide structure controls

src/modules/scheduledDeactivationMethods.ts
=> Fixes on transfer/dismissal mailing

src/components/CorporateTeamsPage/CorporateTeamsPage.tsx, src/modules/organizationUnitMethods.ts, src/trpc/router/organizationUnitRouter.ts
=> Hide empty org-units

src/components/FireOrTransferUserModal/FireOrTransferUserModal.tsx, src/components/UserCreateRequestsPage/UserCreateRequestsPage.module.css, src/components/UserCreateRequestsPage/UserCreateRequestsPage.tsx, src/components/UserFormWorkSpaceDismissalFormBlock/UserFormWorkSpaceDismissalFormBlock.tsx, src/modules/modules.i18n/en.json, src/modules/modules.i18n/ru.json, src/modules/userCreationRequestMethods.ts, src/pages/requests/users/transfer-intern-to-staff/[requestId]/edit.tsx, src/pages/requests/users/transfer-intern-to-staff/[requestId]/index.tsx, src/pages/users/[userId]/transfer-intern-to-staff.tsx, src/trpc/router/userCreationRequestRouter.ts, src/utils/emailTemplates.ts, src/utils/utils.i18n/en.json, src/utils/utils.i18n/ru.json
=> Emails for transfer intern to staff

src/components/HistoryRecord/HistoryRecord.i18n/en.json, src/components/HistoryRecord/HistoryRecord.i18n/ru.json, src/components/HistoryRecord/HistoryRecord.tsx, src/components/TransferInternToStaffPage/TransferInternToStaffPage.tsx, src/modules/groupRoleMethods.ts, src/modules/historyEventTypes.ts, src/modules/userCreationRequestMethods.ts, src/modules/userCreationRequestSchemas.ts, src/trpc/router/userCreationRequestRouter.ts, src/utils/transferInterntoStaffHistoryEvent.ts, src/worker/create.ts, src/worker/resolve.ts
=> Logs for transfer intern to staff

src/trpc/router/restRouter.ts
=> Employment info rest endpoint

src/components/AccessCoordinationList/AccessCoordinationList.tsx, src/components/ExternalFromMainOrgUserCreationRequestPage/ExternalFromMainOrgUserCreationRequestPage.tsx, src/components/ExternalUserCreationRequestPage/ExternalUserCreationRequestPage.tsx, src/components/InternalUserCreationRequestPage/InternalUserCreationRequestPage.tsx, src/utils/emailTemplates.ts
=> Return decide buttons

src/utils/emailTemplates.ts, src/worker/index.ts, src/worker/worker.ts
=> Send worker error to sentry

.eslintrc.js, src/components/HistoryRecord/HistoryRecord.i18n/en.json, src/components/HistoryRecord/HistoryRecord.i18n/ru.json, src/components/HistoryRecord/HistoryRecord.tsx
=> Support logs with no data

src/components/UserCreateRequestsPage/UserCreateRequestsPage.i18n/ru.json, src/components/UserCreateRequestsPage/UserCreateRequestsPage.tsx, src/modules/scheduledDeactivationMethods.ts, src/modules/userCreationRequestMethods.ts, src/utils/emailTemplates.ts, src/worker/worker.ts
=> Emails on transfer inside

src/components/RequestFormActions/RequestFormActions.tsx, src/components/UserFormFormActions/UserFormFormActions.tsx, src/components/UserFormTeamBlock/UserFormTeamBlock.tsx, src/components/WarningModal/WarningModal.module.css, src/pages/requests/users/transfer-inside/[requestId]/edit.tsx, src/worker/index.ts
=> Transfer inside fixes

src/components/CreateDecreeForm/CreateDecreeForm.tsx, src/components/UserPage/UserPage.tsx, src/components/UserUpdateForm/UserUpdateForm.i18n/en.json, src/components/UserUpdateForm/UserUpdateForm.i18n/ru.json, src/components/UserUpdateForm/UserUpdateForm.tsx, src/modules/groupMethods.ts, src/modules/userMethods.ts, src/modules/userSchemas.ts, src/modules/userTypes.ts, src/trpc/router/restRouter.ts, src/trpc/router/userRouter.ts, src/worker/resolve.ts
=> Stop using org unit relation in user model

prisma/migrations/20250318124315_user_creation_rest/migration.sql, prisma/schema.prisma, src/components/InternalUserCreationRequestPage/InternalUserCreationRequestPage.i18n/en.json, src/components/InternalUserCreationRequestPage/InternalUserCreationRequestPage.i18n/ru.json, src/components/InternalUserCreationRequestPage/InternalUserCreationRequestPage.tsx, src/components/RequestFormActions/RequestFormActions.i18n/en.json, src/components/RequestFormActions/RequestFormActions.i18n/ru.json, src/components/RequestFormActions/RequestFormActions.tsx, src/components/UserCreateRequestsPage/UserCreateRequestsPage.i18n/en.json, src/components/UserCreateRequestsPage/UserCreateRequestsPage.i18n/ru.json, src/components/UserCreateRequestsPage/UserCreateRequestsPage.module.css, src/components/UserCreateRequestsPage/UserCreateRequestsPage.tsx, src/components/UserFormWorkSpaceBlock/UserFormWorkSpaceBlock.tsx, src/components/WarningModal/WarningModal.module.css, src/components/WarningModal/WarningModal.tsx, src/generated/kyselyTypes.ts, src/modules/historyEventMethods.ts, src/modules/historyEventTypes.ts, src/modules/userCreationRequestHooks.ts, src/modules/userCreationRequestMethods.ts, src/modules/userCreationRequestSchemas.ts, src/trpc/router/restRouter.ts, src/trpc/router/userCreationRequestRouter.ts, src/trpc/trpcBackend.ts, src/utils/notifications/notifications.i18n/en.json, src/utils/notifications/notifications.i18n/ru.json, src/utils/notifications/notificationsMap.ts
=> Rest Api: create draft UserCreationRequest

src/components/HistoryRecord/HistoryRecord.i18n/en.json, src/components/HistoryRecord/HistoryRecord.i18n/ru.json, src/components/HistoryRecord/HistoryRecord.tsx, src/modules/historyEventTypes.ts, src/trpc/router/restRouter.ts
=> Rest Api: resolve UserCreationRequest

prisma/seed.ts
=> Update seed script

src/modules/searchMethods.ts, src/modules/userMethods.ts
=> Global search by login, other email

src/modules/userCreationRequestMethods.ts, src/modules/userCreationRequestSchemas.ts, src/trpc/router/restRouter.ts
=> Rest Api: edit UserCreationRequest

src/components/HistoryRecord/HistoryRecord.tsx, src/components/UserPage/UserPage.tsx, src/components/UserUpdateForm/UserUpdateForm.tsx, src/modules/historyEventTypes.ts, src/modules/serviceMethods.ts, src/modules/userHooks.ts, src/modules/userMethods.ts, src/modules/userSchemas.ts, src/trpc/router/restRouter.ts, src/trpc/router/userRouter.ts, src/utils/supplementalPositions.ts
=> Rest-api: Edit User

package-lock.json, package.json, src/worker/index.ts, src/worker/sentry.ts
=> Add sentry logs

src/utils/regex.ts
=> E YO search

src/components/TeamProfilePreview/TeamProfilePreview.tsx, src/components/UserProfilePreviewAvatar/UserProfilePreviewAvatar.tsx
=> feat(INTERNAL-1734): close preview on show click

src/components/HistoryRecord/HistoryRecord.i18n/en.json, src/components/HistoryRecord/HistoryRecord.i18n/ru.json, src/components/HistoryRecord/HistoryRecord.tsx, src/modules/externalUserMethods.ts, src/modules/historyEventTypes.ts
=> Fix external user methods

src/components/CorporateTeamsPage/CorporateTeamsPage.tsx, src/components/GroupTreeViewNode/GroupTreeViewNode.tsx, src/components/TeamsPage/TeamsPage.tsx, src/components/VirtualTeamsPage/VirtualTeamsPage.tsx, src/hooks/useGroupTreeFilter.ts
=> Fix group node open

src/components/LayoutMain/LayoutMain.tsx, src/components/PageFooter/PageFooter.i18n/en.json, src/components/PageFooter/PageFooter.i18n/ru.json, src/components/PageFooter/PageFooter.tsx, src/components/SheepLogoWithTips/SheepLogoWithTips.i18n/en.json, src/components/SheepLogoWithTips/SheepLogoWithTips.i18n/index.ts, src/components/SheepLogoWithTips/SheepLogoWithTips.i18n/ru.json, src/components/SheepLogoWithTips/SheepLogoWithTips.module.css, src/components/SheepLogoWithTips/SheepLogoWithTips.tsx, src/utils/getRandomIndex.tsx, src/utils/utils.i18n/en.json, src/utils/utils.i18n/ru.json
=> Footer and header edits 

src/modules/userMethods.ts
=> Fix search by email in rest router

src/modules/userCreationRequestMethods.ts
=> Fix ical method on cancelling event

src/modules/userCreationRequestMethods.ts
=> Correct time for transfer newcommer event

src/modules/externalUserMethods.ts, src/modules/externalUserTypes.ts, src/modules/userMethods.ts, src/utils/getUnitGroup.ts
=> Send unit to external user create

src/components/UserFormAttaches/UserFormAttaches.tsx, src/modules/scheduledDeactivationMethods.ts, src/worker/create.ts
=> Scheduled deactivation fixes

src/components/CreateDecreeForm/CreateDecreeForm.tsx, src/components/UserPage/UserPage.i18n/en.json, src/components/UserPage/UserPage.i18n/ru.json, src/components/UserPage/UserPage.tsx, src/modules/modules.test.ts, src/modules/userCreationRequestSchemas.ts, src/modules/userMethods.ts, src/modules/userSchemas.ts, src/modules/userTypes.ts
=> Decree user state and profile reactivation

src/components/HistoryRecord/HistoryRecord.i18n/en.json, src/components/HistoryRecord/HistoryRecord.i18n/ru.json, src/components/HistoryRecord/HistoryRecord.tsx, src/modules/historyEventTypes.ts, src/modules/supplementalPositionMethods.ts, src/trpc/router/supplementalPositionRouter.ts, src/utils/userCreationRequestHistoryEvents.ts
=> Logs for supplemental position requests

src/modules/modules.i18n/en.json, src/modules/modules.i18n/ru.json, src/modules/userCreationRequestSchemas.ts
https://github.com/user-attachments/assets/8f2764f1-7d83-4527-98c9-fa1e9f09a8a4
=> Validating dates in forms

src/trpc/router/scheduledDeactivationRouter.ts, src/utils/dateTime.ts
=> Activate user when deactivation request date changes

prisma/migrations/20250423085658_user_device_id/migration.sql, prisma/schema.prisma, src/generated/kyselyTypes.ts
=> Add id to user device model

src/components/UserFormRegistrationBlock/UserFormRegistrationBlock.tsx, src/modules/externalUserMethods.ts, src/trpc/router/userCreationRequestRouter.ts
=> Deactivate external account for approved requests

src/components/RequestFormActions/RequestFormActions.tsx, src/components/UserPage/UserPage.tsx, src/modules/supplementalPositionHooks.ts, src/modules/supplementalPositionMethods.ts, src/worker/resolve.ts
=> Fixes for supplemental position request

src/components/UserPage/UserPage.tsx
=> Correct access check for new supplemental position button

src/modules/externalUserMethods.ts
=> User no found fix

src/modules/userCreationRequestSchemas.ts
=> Convert email to lowercase when creating users

src/trpc/router/restRouter.ts, src/trpc/trpcBackend.ts
=> Add api roles

src/components/DecreeForm/DecreeForm.tsx, src/components/UserFormAttaches/UserFormAttaches.tsx, src/components/UserFormCommentsBlock/UserFormCommentsBlock.tsx, src/components/UserFormRegistrationBlock/UserFormRegistrationBlock.tsx
=> Decree attaches

prisma/migrations/20250423134015_remove_device_user_unique/migration.sql, prisma/schema.prisma, src/components/CreateDecreeForm/CreateDecreeForm.tsx, src/generated/kyselyTypes.ts, src/modules/deviceMethods.ts, src/modules/userMethods.ts
=> Archive user devices

src/utils/emailTemplates.ts
=> Check if domainIds not empty

src/components/DecreeForm/DecreeForm.tsx, src/components/UserFormAttaches/UserFormAttaches.tsx, src/components/UserFormCommentsBlock/UserFormCommentsBlock.tsx, src/components/UserFormRegistrationBlock/UserFormRegistrationBlock.tsx
=> Support attaches

src/components/UserPage/UserPage.tsx
=> Remove extra notification

src/modules/userCreationRequestSchemas.ts
=> fix(INTERNAL-1847): Convert email to lowercase when creating users

src/components/HistoryRecord/HistoryRecord.tsx, src/components/SameNameAlert/SameNameAlert.i18n/en.json, src/components/SameNameAlert/SameNameAlert.i18n/index.ts, src/components/SameNameAlert/SameNameAlert.i18n/ru.json, src/components/SameNameAlert/SameNameAlert.module.css, src/components/SameNameAlert/SameNameAlert.tsx, src/components/UserCreateRequestsPage/UserCreateRequestsPage.tsx, src/components/UserFormPersonalDataBlock/UserFormPersonalDataBlock.module.css, src/components/UserFormPersonalDataBlock/UserFormPersonalDataBlock.tsx, src/modules/userHooks.ts, src/modules/userMethods.ts, src/modules/userSchemas.ts, src/trpc/router/userRouter.ts, src/utils/emailTemplates.ts, src/utils/userCreationRequests.ts
=> Same name alerts in requests

prisma/migrations/20250506195723_user_requests_completed_status/migration.sql, prisma/schema.prisma, src/components/DecreeForm/DecreeForm.tsx, src/components/RequestFormActions/RequestFormActions.tsx, src/components/UserCreateRequestsPage/UserCreateRequestsPage.i18n/en.json, src/components/UserCreateRequestsPage/UserCreateRequestsPage.i18n/ru.json, src/components/UserCreateRequestsPage/UserCreateRequestsPage.tsx, src/components/UserFormAttaches/UserFormAttaches.tsx, src/components/UserFormPersonalDataBlock/UserFormPersonalDataBlock.tsx, src/components/UserFormWorkSpaceBlock/UserFormWorkSpaceBlock.i18n/en.json, src/components/UserFormWorkSpaceBlock/UserFormWorkSpaceBlock.i18n/ru.json, src/components/UserFormWorkSpaceBlock/UserFormWorkSpaceBlock.tsx, src/config.ts, src/generated/kyselyTypes.ts, src/modules/modules.i18n/en.json, src/modules/modules.i18n/ru.json, src/modules/userCreationRequestMethods.ts, src/modules/userCreationRequestSchemas.ts, src/modules/userMethods.ts, src/utils/emailTemplates.ts, src/utils/utils.i18n/en.json, src/utils/utils.i18n/ru.json
=> Decree fixes
